
name: Push stack to heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release Server
      uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "golang-crud"
        heroku_email: ${{secrets.HEROKU_API_KEY}}
      env:
        HD_APP_BASE: "./"